# Generated by Django 5.2 on 2025-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlanse_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
