# Generated by Django 5.2 on 2025-06-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlanse_book', '0002_flightmodel_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('On time', 'Ontime'), ('Delayed', 'Delayed'), ('Departed', 'Departed'), ('Landed', 'Landed'), ('Check in closed', 'Check In Closed')], default='Scheduled'),
        ),
    ]
